name: Trigger workflow in Ship Shoot repo

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  trigger:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger workflow in Ship Shoot repo
      uses: peter-evans/repository-dispatch@v3
      with:
        token: "${{ secrets.PAT_TOKEN }}"
        repository: FarzadBT/ship-shoot
        event-type: Integration-with-Automation